### ISSUE TITLE
Compiled bundle fails to load driver kext under Mojave

### ISSUE THREAD

**Issue by mackonsti** [1hbb/OpenIntelWireless-Factory#1]
Hello @1hbb and thanks for setting up the auto-compiled packages for us, it is a real life-saver for those not comfortable with Xcode. However I'd like to report an issue with your recent released packages, namely under Mojave.

I downloaded yesterday's package https://github.com/1hbb/OpenIntelWireless-Factory/releases/tag/2020-07-18 and while trying to load the kext and make sure it runs well, I keep getting the following errors, using `kextutil -t` to verbose, after setting `chown -R root:wheel itlwm.kext` of course:

```
$ sudo kextutil -t itlwm.kext

Kext with invalid signatured (-67062) allowed: <OSKext 0x7fca13e0cf20 [0x7fff896918f0]> { URL = "file:///Users/mackonsti/Downloads/itlwm.kext/", ID = "com.zxystd.itlwm" }
Code Signing Failure: not code signed
Disabling KextAudit: SIP is off
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV13IOEventSource' for vtable '__ZTV11IOTaskQueue' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV19IOEthernetInterface' for vtable '__ZTV15itlwm_interface' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV8OSObject' for vtable '__ZTV15pci_intr_handle' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV20ItlNetworkUserClient' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV20IOEthernetController' for vtable '__ZTV5itlwm' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV8OSObject' for vtable '__ZTV8CTimeout' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.zxystd.itlwm - link failed.
(kernel) Failed to load executable for kext com.zxystd.itlwm.
(kernel) Kext com.zxystd.itlwm failed to load (0xdc008016).
(kernel) Failed to load kext com.zxystd.itlwm (error 0xdc008016).
Failed to load /Users/mackonsti/Downloads/itlwm.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```

There is something in the compilation parameters that makes the resulting **itlwm.kext** not load under Mojave. I hope you can help, not sure if others reported this already. I am not on Catalina on which the package seems to work as expected. On the other hand, **HeliPort.app** works and loads perfectly.

Thank you in advance, let me know if I can be of further assistance.

**Comment by 1hbb** [comment]
Did you try to copy itlwm.kext to /EFI/OC/Kexts or kext folder in clover and restart. Its most common way.

**Comment by mackonsti** [comment]
Hi @1hbb no, to be honest. I am still under Mojave and using the old mentality of `/L/E/` for all kexts.
But if I use another script shared over in the main **itlwm** Issues thread, the kext works and loads.
Not necessarily from `/L/E/` but from `~/Downloads` with `chown -R 0:0 itlwm.kext` of course.
I think it's related to the automation build parameters not the way it's loaded. Hope this helps.

**Comment by mackonsti** [comment]
Here is [the bash script](https://github.com/OpenIntelWireless/itlwm/issues/158#issuecomment-653849705) (slightly modified for Mojave) that I can run manually to create a working build under Mojave. Please note that this scripts also deletes all firmware and leaves only the one that I need, making the driver more compact:

```
#!/bin/bash

# remove all local changes
git reset --hard HEAD
rm -rf build

# pull latest code
git pull

# remove generated firmware
rm itlwm/FwBinary.cpp

# remove firmware for other wifi cards - DELETE OR CHANGE TO YOUR CARD
find itlwm/firmware/ -type f ! -name 'iwm-9000-34' -delete

# set version as commit count
version=`git rev-list HEAD | wc -l | tr -d ' '`
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :CFBundleShortVersionString $version"
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :CFBundleVersion $version"

# make the product a kext
packagetype="KEXT"
minimumversion="10.13"
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :CFBundlePackageType $packagetype"
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Add :LSMinimumSystemVersion string $minimumversion"

# add my networks - CHANGE TO YOUR NETWORKS
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :IOKitPersonalities:itlwm:WiFiConfig:WiFi_1:ssid TEST"
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :IOKitPersonalities:itlwm:WiFiConfig:WiFi_1:password TEST"

# /usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :IOKitPersonalities:itlwm:WiFiConfig:WiFi_2:ssid Y"
# /usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :IOKitPersonalities:itlwm:WiFiConfig:WiFi_2:password YYY"

# /usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :IOKitPersonalities:itlwm:WiFiConfig:WiFi_3:ssid Z"
# /usr/libexec/PlistBuddy itlwm/Info.plist -c "Set :IOKitPersonalities:itlwm:WiFiConfig:WiFi_3:password ZZZ"

# remove unused network(s)
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Delete :IOKitPersonalities:itlwm:WiFiConfig:WiFi_2"
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Delete :IOKitPersonalities:itlwm:WiFiConfig:WiFi_3"
/usr/libexec/PlistBuddy itlwm/Info.plist -c "Delete :IOKitPersonalities:itlwm:WiFiConfig:WiFi_4"

echo "Will build project in 5 seconds..." && sleep 5

# generate firmware
xcodebuild -project itlwm.xcodeproj -target fwgen -configuration Release -sdk macosx

# build the kext
xcodebuild -project itlwm.xcodeproj -target itlwm -configuration Release -sdk macosx 
```
Could it be your SDK parameter? Setting it to plain `macosx` works for Mojave. The above works and each kext gets to load fine. I have also discovered that both parameters are absolutely needed under Mojave:
```
CFBundlePackageType = "KEXT"
LSMinimumSystemVersion = "10.13"
```

**Comment by 1hbb** [comment]
Can you try this [kext](https://github.com/1hbb/itlwmx-heliport/releases/download/2020-07-18/HeliPort-itlwm-itlwmx.zip).

**Comment by mackonsti** [comment]
I am sorry @1hbb :-(

```
$ sudo kextutil -v itlwm.kext

Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fb2a2d11650 [0x7fff90e968f0]> { URL = "file:///Users/mackonsti/Downloads/HeliPort-itlwm-itlwmx/itlwm.kext/", ID = "com.zxystd.itlwm" }
Code Signing Failure: code signature is invalid
/Users/konsti/Zoolook/HeliPort-itlwm-itlwmx/itlwm.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Users/konsti/Zoolook/HeliPort-itlwm-itlwmx/itlwm.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV13IOEventSource' for vtable '__ZTV11IOTaskQueue' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV19IOEthernetInterface' for vtable '__ZTV15itlwm_interface' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV8OSObject' for vtable '__ZTV15pci_intr_handle' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV20ItlNetworkUserClient' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV20IOEthernetController' for vtable '__ZTV5itlwm' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV8OSObject' for vtable '__ZTV8CTimeout' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.zxystd.itlwm - link failed.
(kernel) Failed to load executable for kext com.zxystd.itlwm.
(kernel) Kext com.zxystd.itlwm failed to load (0xdc008016).
(kernel) Failed to load kext com.zxystd.itlwm (error 0xdc008016).
Failed to load /Users/mackonsti/Downloads/HeliPort-itlwm-itlwmx/itlwm.kext - (libkern/kext) link error.
Failed to load /Users/mackonsti/Downloads/HeliPort-itlwm-itlwmx/itlwm.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).

$ kextlibs itlwm.kext

For all architectures:
    com.apple.iokit.IONetworkingFamily = 3.4
    com.apple.iokit.IOPCIFamily = 2.9
    com.apple.kpi.bsd = 18.7
    com.apple.kpi.iokit = 18.7
    com.apple.kpi.libkern = 18.7
    com.apple.kpi.mach = 18.7

For x86_64:
    14 symbols not found in any library kext.

$ sudo kextload -v itlwm.kext

Requesting load of /Users/mackonsti/Downloads/HeliPort-itlwm-itlwmx/itlwm.kext.
/Users/mackonsti/Downloads/HeliPort-itlwm-itlwmx/itlwm.kext failed to load - (libkern/kext) link error; check the system/kernel logs for errors or try kextutil(8).
```

P.S. There's a `_CodeSignature` folder inside the kext, I think it's really useless i.e. not valid or even taken into consideration by the system. Not related to the above, of course, just a reminder to remove it perhaps... Let me know how I can help.

**Comment by mackonsti** [comment]
Hello @1hbb I understand you may be busy but please know, today's downloaded build 21-7-2020 can still not load under Mojave.

```
$ sudo chown -R 0:0 itlwm.kext
Password:

$ sudo kextutil -v itlwm.kext

Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fa83ce02ba0 [0x7fff90e968f0]> { URL = "file:///Users/mackonsti/Downloads/itlwm.kext/", ID = "com.zxystd.itlwm" }
Code Signing Failure: code signature is invalid
/Users/mackonsti/Downloads/itlwm.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Users/konsti/Zoolook/itlwm.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV13IOEventSource' for vtable '__ZTV11IOTaskQueue' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV19IOEthernetInterface' for vtable '__ZTV15itlwm_interface' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV8OSObject' for vtable '__ZTV15pci_intr_handle' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV20ItlNetworkUserClient' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV20IOEthernetController' for vtable '__ZTV5itlwm' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.zxystd.itlwm]: The super class vtable '__ZTV8OSObject' for vtable '__ZTV8CTimeout' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.zxystd.itlwm - link failed.
(kernel) Failed to load executable for kext com.zxystd.itlwm.
(kernel) Kext com.zxystd.itlwm failed to load (0xdc008016).
(kernel) Failed to load kext com.zxystd.itlwm (error 0xdc008016).
Failed to load /Users/mackonsti/Downloads/itlwm.kext - (libkern/kext) link error.
Failed to load /Users/mackonsti/Downloads/itlwm.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```
I hope you can crack this puzzle soon. Thank you.

**Comment by 1hbb** [comment]
There is no solution for this problem. Most of Hackintosh kexts will give `Code Signing Failure: code signature is invalid` error if you try to install it with `sudo kextutil` command. The only solution i know is signing kext with apple developer account but I don't have one. İf you want to install itlwm.kext to `/S/L/E` you can install kext with [Kext-Droplet](https://github.com/chris1111/Kext-Dropletl) app. I tried its working. But I don't recommend installing kext `/S/L/E` because its so risky.

**Comment by mackonsti** [comment]
Hi @1hbb thanks for your reply. The issue is _not_ the signature.

The issue is the linking errors. Something in the build parameters are just not done for earlier than Catalina.
That's why I posted the script that works, above.
When loading the kext build with that script, there are no such errors as "class table" etc. when loaded with kextutil...
Not sure if it's the automated build parameters OR the system on which you build the kexts?

Can you share more information on the script itself and the machine? Do you force an SDK e.g. `macosx10.13` ?
(source https://stackoverflow.com/questions/4314804/parameter-for-xcodebuild-for-using-latest-sdk)

Thanks!

**Comment by 1hbb** [comment]
Can u try this kext. Its worked on my system. 
[itlwm.kext.zip](https://github.com/1hbb/OpenIntelWireless-Factory/files/4960719/itlwm.kext.zip)

```
buraks-MacBook-Pro:React burak$ sudo chown -R 0:0 itlwm.kext
Password:
buraks-MacBook-Pro:React burak$ sudo kextutil -v itlwm.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signature (-67050) allowed: <OSKext 0x7fe47140d060 [0x7fff8c3b08c0]> { URL = "file:///Users/burak/Desktop/React/itlwm.kext/", ID = "com.zxystd.itlwm" }
Code Signing Failure: code signature is invalid
/Users/burak/Desktop/React/itlwm.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Users/burak/Desktop/React/itlwm.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
/Users/burak/Desktop/React/itlwm.kext successfully loaded (or already loaded).
Invalid signature -67050 for kext <OSKext 0x7fe47140d060 [0x7fff8c3b08c0]> { URL = "file:///Users/burak/Desktop/React/itlwm.kext/", ID = "com.zxystd.itlwm" }
```

**Comment by mackonsti** [comment]
Hi @1hbb I am sorry, I get the same results as before.
```
(kernel) kxld[com.zxystd.itlwm]: The super class vtable XXX is out of date. Make sure your kext has been built against the correct headers.
```

Are you running Catalina?

I now remembered that upon first `xcodebuild` run, I had to install **Mojave headers** that are removed from newer Xcode: https://donatstudios.com/MojaveMissingHeaderFiles

```
$ sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```

Are you compiling these on your own machine or a VM?
What SDK are you defining as parameter?
Thanks

**Comment by 1hbb** [comment]
Kext compiling on cloud based vm. As you said maybe problem about ` Mojave headers`. I will try it.
i did it as you said. (vm system macos 10.14 ).


[itlwm.kext.zip](https://github.com/1hbb/OpenIntelWireless-Factory/files/4969707/itlwm.kext.zip)

**Comment by mackonsti** [comment]
Hi @1hbb thank you for your effort, but it still doesn't load. I tried it twice from scratch. Did you reboot the VM after applying the package? Just wondering, you never know... did the headers install OK in Terminal, you didn't get any errors, yes?

I am not sure what's happening, are you loading `itlmw.kext` fine on your Mojave? Looks like I am the only one left back in 10.14 everyone is on Catalina... so I am curious why no-one else reported this same "link failed" error due to headers.

I don't copy paste the output error, as it's the same, _The super class vtable XYZ is out of date. Make sure your kext has been built against the correct headers._

As you see it was reported some time ago here too https://github.com/OpenIntelWireless/itlwm/issues/76

According to https://apple.stackexchange.com/questions/384343/mojave-usb-ethernet-adapter-kext-wrong-headers-lib-declarations

> ...a mismatch between the SDK version you are building against and the OS X version you are trying to load your kext on.Unlike OS X userspace, setting the "Deployment Target" to the minimum OS X version supported by your driver is not sufficient.must also use the OS X SDK version matching the oldest supported OS X version for this very reason of reserved virtual functions. e.g. maybe you're building with the 10.10 or 10.11 SDK,but are trying to load the kext on 10.9. That won't work. Use Xcode 6.3.2 (the newest version that ships with the 10.9 SDK), select the 10.9 SDK, and build with that."

Perhaps there's a need to tweak your `xcodebuild` parameters. Hope this helps. Thank you.

**Comment by 1hbb** [comment]
@mackonsti can u try this. 
[itlwm.kext.zip](https://github.com/1hbb/OpenIntelWireless-Factory/files/4978188/itlwm.kext.zip)
Used macOS 10.12 SDK.

**Comment by mackonsti** [comment]
Congratulations! It works on Mojave! Many thanks!

```
$ sudo kextutil -v itlwm.kext

Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f8f0a50a280 [0x7fff879fc8f0]> { URL = "file:///Users/mackonsti/Downloads/itlwm.kext/", ID = "com.zxystd.itlwm" }
Code Signing Failure: not code signed
/Users/mackonsti/Downloads/itlwm.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Users/mackonsti/Downloads/itlwm.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
/Users/mackonsti/Downloads/itlwm.kext successfully loaded (or already loaded).
```

Please keep what you did for next releases. Many thanks :-)

**Comment by 1hbb** [comment]
Changes applied on repo. You can use versions after 2020-07-26. I will close this issue. İf you have problem you can open. Thank you too.

**Comment by borygo77** [comment]
edit:  I'm so stupid :D Just tried itlwmx.kext and it's working ok for me! 



Hi guys! Had the same as the op for couple days on mojave but new releases installing fine!
But still can't get it to work on my system with intel ax200 :( Do I need to do anything special to get this to work ? There is itlwmx.kext in release bundle.. What is it for ? 

![Pasted Graphic](https://user-images.githubusercontent.com/43052061/89103656-4674a600-d40b-11ea-8803-188cf50fa4a1.png)
![Pasted Graphic 2](https://user-images.githubusercontent.com/43052061/89103658-496f9680-d40b-11ea-95db-545a3c6be605.png)
