### ISSUE TITLE
The version auto compiled is old

### ISSUE THREAD

**Issue by AnimaMusic1998** [1hbb/OpenIntelWireless-Factory#12]
The version auto compiled is old because in openintelwirless 1.1.0 stable is new. Please upload.
![E96A7152-4FD5-47B1-87C4-E2719C653969](https://user-images.githubusercontent.com/67318166/93431769-e6f02e00-f8c4-11ea-9f14-1b6a9211438f.png)

**Comment by 1hbb** [comment]
Its not old. Every day creating one tag like 2020-09-17 an this tag updating every 8 hours.

**Comment by AnimaMusic1998** [comment]
> Its not old. Every day creating one tag like 2020-09-17 an this tag updating every 8 hours.

But itlwmx Is deprecated with version 1.1.0 stable
![A07E6874-E5C8-486E-ACB8-A4D419A16C1D](https://user-images.githubusercontent.com/67318166/93477699-9fd15f80-f8fb-11ea-8560-4b02f5974c89.png)

Can you change the title of the kext? and I noticed that auto-filling is not always 8 hours

![8A31551A-4E8F-475B-BB99-ECE5F572CBA1](https://user-images.githubusercontent.com/67318166/93477668-97792480-f8fb-11ea-9524-218b7bc1c188.png)

![0FC29D8A-8BFD-454D-88E8-F3B17C7AEAA4](https://user-images.githubusercontent.com/67318166/93477974-df984700-f8fb-11ea-963b-7b09bd9d963b.png)

**Comment by 1hbb** [comment]
Okey. I will change title like 2020-09-17-20:19

**Comment by Emanuele-1998** [comment]
there is also the kext for Big Sur and for Catina while on your repo there is only itlwmx-stable

![6F99172F-8727-48D6-B0ED-317E0C7ECEAD](https://user-images.githubusercontent.com/67318166/93581394-64896c00-f9a1-11ea-84e1-772e44054fee.png)
![58E3EE71-D84D-46F5-9DDF-EFCBC0D5019E](https://user-images.githubusercontent.com/67318166/93581396-65ba9900-f9a1-11ea-856a-21c074a33f00.png)
