### ISSUE TITLE
HeliPort is running from an unexpected path

### ISSUE THREAD

**Issue by Tomanight** [1hbb/OpenIntelWireless-Factory#2]
![image](https://user-images.githubusercontent.com/67735842/87944270-cbcb9280-cabc-11ea-8909-c7f2a0fbe7ec.jpg)
Hi @1hbb . I have placed my heliport app into applications and set it to start on login and I have placed my itlwm.kext into EFI/Clover/kexts/other and after restart when thr heliport app opens it says that it is running from an unexpected place. Did i place my kext or app wrong. Please advice

**Comment by mehmetyukcell** [comment]
Yes, 
![Ekran Resmi 2020-07-20 16 50 57](https://user-images.githubusercontent.com/62822060/87946181-5bb41100-caaa-11ea-8a22-e7eb0000dcf9.png)

**Comment by 1hbb** [comment]
can both of you redownload latest release an try it again. [Latest Release](https://github.com/1hbb/OpenIntelWireless-Factory/releases/tag/2020-07-20l)

**Comment by Tomanight** [comment]
Doing it so with the latest release started this issue. The previous version worked perfectly without a hitch. But now when I try to install the previous version, with the kext and app from yesterday's version, i get the same problem. I also used cleanmymac to clear off all junk files after uninstalling heliport, after cleaning off junk files, I also restarted my hackintosh, and installed it again, that also did nothing.

**Comment by 1hbb** [comment]
> Doing it so with the latest release started this issue. The previous version worked perfectly without a hitch. But now when I try to install the previous version, with the kext and app from yesterday's version, i get the same problem. I also used cleanmymac to clear off all junk files after uninstalling heliport, after cleaning off junk files, I also restarted my hackintosh, and installed it again, that also did nothing.

Are you sure you downloaded the latest [version](https://github.com/1hbb/OpenIntelWireless-Factory/releases/download/2020-07-20/HeliPort-itlwm-itlwmx.zip) again ?

**Comment by Tomanight** [comment]
After 3 tries, its working. Thank you.

**Comment by candyrock** [comment]
I have same an issue

**Comment by Tomanight** [comment]
> I have same an issue

Redownload the zip file and do it again its working

**Comment by candyrock** [comment]
> > I have same an issue
> 
> Redownload the zip file and do it again its working

i tried redownload many times but can not open

**Comment by candyrock** [comment]
fixed with new latest

**Comment by 1hbb** [comment]
Deleta all HeliPort.app on your system before installing heliport again.  I will close it

**Comment by md-siam** [comment]
Use AppCleaner to remove HeliPort app completely(including any leftovers). https://freemacsoft.net/appcleaner/
