### ISSUE TITLE
Add Support Monterey zip

### ISSUE THREAD

**Issue by AnimaMusic1998** [1hbb/OpenIntelWireless-Factory#21]
Hi, add download monterey zip, thanks. ![image](https://user-images.githubusercontent.com/67318166/121233529-0126cd80-c893-11eb-8200-5507ded855ad.png)

Official Repo

![image](https://user-images.githubusercontent.com/67318166/121233583-0edc5300-c893-11eb-8dd9-ff8667732b61.png)

**Comment by 1hbb** [comment]
Thanks for warning. I will care about it
