### ISSUE TITLE
Link speed in 5GHz is only 100Mbps

### ISSUE THREAD

**Issue by md-siam** [1hbb/OpenIntelWireless-Factory#4]
![Screen Shot 2020-07-21 at 11 56 54 AM](https://user-images.githubusercontent.com/21225918/88018518-b2245c80-cb49-11ea-8d33-03913182c71a.png)

Link in 5GHz is only 100Mbps, can you please increase this link speed. 
Thanks

**Comment by 1hbb** [comment]
This repo only compile itlwm.kext and HeliPort.app from [here](https://github.com/OpenIntelWireless). You can write issue to official project page.

**Comment by md-siam** [comment]
Thanx for your reply 🙂

**Comment by 1hbb** [comment]
thanks to you i will close issue
