### ISSUE TITLE
Why AC 8260 is not listed in README

### ISSUE THREAD

**Issue by chris1111** [1hbb/OpenIntelWireless-Factory#5]
Its work here Big Sur and Catalina with **itlwm.kext**
![Screen Shot 2020-08-01 at 4 19 40 PM](https://user-images.githubusercontent.com/6248794/89109890-3c56a580-d413-11ea-8071-b58750a59e04.png)
![Screen Shot 2020-08-01 at 4 23 42 PM](https://user-images.githubusercontent.com/6248794/89110534-6d39d900-d419-11ea-9ca6-9097db9aee97.png)

I am using a [PCE AC55BT b1](https://www.amazon.ca/Asus-PCE-AC55BT-B1-Wireless-AC1200-Bluetooth/dp/B0713RRZMB)

**Comment by md-siam** [comment]
Yes, it supports 8000 series cards. But there are no users to report it.
Check here: https://github.com/OpenIntelWireless/itlwm/blob/master/.github/README_en.md 

Kindly tell this information in gitter chat: https://gitter.im/OpenIntelWireless/itlwm?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
