### ISSUE TITLE
do you need the itlwmx.kext in addition to itlwm.kext

### ISSUE THREAD

**Issue by myusrn** [1hbb/OpenIntelWireless-Factory#6]
Do you need to add itlwmx.kext in addition to itlwm.kext to your opencore kexts folder?  

What's the role of the itlwmx.kext given in past i've been able to enable intel wifi interface using just the itlwm.kext?

**Comment by 1hbb** [comment]
itlwmx.kext for intel x series wifi cards like ax200.

**Comment by myusrn** [comment]
Thanks for clarification. That's great to hear ax200 adapters are covered. Do you know know if there is any issues having both kexts present in kexts folder, i.e. will system just load and enable one matching the ac or ax m.2 adapters found in system?

**Comment by 1hbb** [comment]
Use only one of these.  I think it will give error if you try to use both of them together.

**Comment by myusrn** [comment]
got it, thanks for clarifications and additional details.
