### ISSUE TITLE
Unable to connect Intel 8265

### ISSUE THREAD

**Issue by bobwhite1x** [1hbb/OpenIntelWireless-Factory#7]
![20200822_000749](https://user-images.githubusercontent.com/70043439/90945739-13518f80-e46a-11ea-8b60-28d8fdb486c7.jpg)
Its showing an exclamation mark after connecting, did a restart and reset the router but no luck.
internet works on all other devices so its not router issue. tried to use a old version of heliport app the exclamation doesn't appear(shows connected but with no tick mark and no internet)

**Comment by 1hbb** [comment]
This repo for auto compile itlwm and HeliPort. You can write your issue [here](https://github.com/OpenIntelWireless/HeliPort)
