### ISSUE TITLE
Autocompile

### ISSUE THREAD

**Issue by influenist** [1hbb/OpenIntelWireless-Factory#8]
Hi @1hbb , seems the autocompile stopped working. Please fix if possible :-)

**Comment by 1hbb** [comment]
Problem fixed. But now there is no itlwmx.kext for now. Because developer removed it from source code. I dont know why.

**Comment by 1hbb** [comment]
Problem fixed. But now there is no itlwmx.kext for now. Because developer removed it from source code. I dont know why.
