### ISSUE TITLE
Intel Wifi 6 AX200 Issue low speed

### ISSUE THREAD

**Issue by fjmatos** [1hbb/OpenIntelWireless-Factory#9]
First of all, congratulations for this project, I been searching and searching for the kext that fit with my hardware , and these are the best of all I´ve found. 

I have a hackintosh with the following specs.

Aorus Z390 PRO
i5 9400K
16 RAM
1TB nvme m2
OpenCore 0.6.1

And I have an Intel Wifi 6 AX200 + Bt card

I have configured the kext of this repo and they had worked for me since the very first moment. 
I have used Heliport and I have been able to connect to my home Wi-Fi AP. 

The two issues that  I have are:

- I do not see  AirDrop in my Mac,  to transfer file from iphone / Ipad to Hackintosh.

- The speed is very low because of the 2.4GHZ / 5GHz band. I have 600 MB fiber optics connection  and with the  1Gbps ethernet
I reach 600 Mbps using using Speedted, but with the Wifi card I  only reach  up to :   UP (33 Mbps) / DOWN (20 Mbps)

**Comment by md-siam** [comment]
1. AirDrop does not work with any Intel Wifi card.
2. Right now, the Heliport only supports 802.11n connection with speed up to 100Mbps.

**Comment by fjmatos** [comment]
@md-siam  Thank you very much. I´ll stay tuned for the next updates.

**Comment by md-siam** [comment]
You can replace your existing WiFi card with a Broadcom WiFi card to get all the functionality like AirDrop & HandOff.

**Comment by fjmatos** [comment]
Yes, just now , I´m looking for one not very expensible to buy from spain .  Broadcom usually works OOB. 
So I´ll follow your recomendation and I replace it for one Broadcom compatible card. THX.
